In [1]:
import numpy as np
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import precision_recall_curve
from sklearn.metrics import classification_report
from sklearn.naive_bayes import BernoulliNB
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.cross_validation import train_test_split
import matplotlib.pyplot as plt
import pandas as pd

D:\Anaconda3\lib\site-packages\sklearn\cross_validation.py:41: DeprecationWarning: This module was deprecated in version 0.18 in favor of the model_selection module into which all the refactored classes and functions are moved. Also note that the interface of the new CV iterators are different from that of this module. This module will be removed in 0.20.
  "This module will be removed in 0.20.", DeprecationWarning)


In [2]:
####knn最邻近算法####
inputfile = 'sales_data.xls'
data = pd.read_excel(inputfile, index_col = u'序号') #导入数据

In [3]:
data

天气 是否周末 是否有促销 销量
序号                 
1   坏    是     是  高
2   坏    是     是  高
3   坏    是     是  高
4   坏    否     是  高
5   坏    是     是  高
6   坏    否     是  高
7   坏    是     否  高
8   好    是     是  高
9   好    是     否  高
10  好    是     是  高
11  好    是     是  高
12  好    是     是  高
13  好    是     是  高
14  坏    是     是  低
15  好    否     是  高
16  好    否     是  高
17  好    否     是  高
18  好    否     是  高
19  好    否     否  高
20  坏    否     否  低
21  坏    否     是  低
22  坏    否     是  低
23  坏    否     是  低
24  坏    否     否  低
25  坏    是     否  低
26  好    否     是  低
27  好    否     是  低
28  坏    否     否  低
29  坏    否     否  低
30  好    否     否  低
31  坏    是     否  低
32  好    否     是  低
33  好    否     否  低
34  好    否     否  低

In [4]:
#数据预处理
data[data == u'好'] = 1
data[data == u'是'] = 1
data[data == u'高'] = 1
data[data != 1] = -1
x = data.iloc[:,:3].as_matrix().astype(int)
y = data.iloc[:,3].as_matrix().astype(int)

In [14]:
data == u'好'

天气   是否周末  是否有促销     销量
序号                            
1   False  False  False  False
2   False  False  False  False
3   False  False  False  False
4   False  False  False  False
5   False  False  False  False
6   False  False  False  False
7   False  False  False  False
8   False  False  False  False
9   False  False  False  False
10  False  False  False  False
11  False  False  False  False
12  False  False  False  False
13  False  False  False  False
14  False  False  False  False
15  False  False  False  False
16  False  False  False  False
17  False  False  False  False
18  False  False  False  False
19  False  False  False  False
20  False  False  False  False
21  False  False  False  False
22  False  False  False  False
23  False  False  False  False
24  False  False  False  False
25  False  False  False  False
26  False  False  False  False
27  False  False  False  False
28  False  False  False  False
29  False  False  False  False
30  False  False  False  False
31  False  False  False  False
32  False  False  False  False
33  False  False  False  False
34  False  False  False  False

In [15]:
import numpy as np
from sklearn.preprocessing import OneHotEncoder

enc = OneHotEncoder()

NameError: name 'data_x' is not defined

In [7]:
y

array([ 1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1, -1,  1,  1,  1,
        1,  1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1])

In [8]:
####SVM####
from sklearn.svm import SVC
clf =SVC()
clf.fit(x_train, y_train)  

SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto', kernel='rbf',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False)

In [9]:
#测试结果
answer = clf.predict(x_test)
print(x_test)
print(answer)
print(y_test)
print(np.mean( answer == y_test))
print(classification_report(y_test, answer, target_names = ['低', '高']))

[[ 1  1  1]
 [ 1 -1 -1]
 [ 1  1  1]
 [ 1  1  1]
 [-1  1  1]
 [ 1 -1  1]
 [-1 -1 -1]]
[ 1 -1  1  1  1 -1 -1]
[ 1 -1  1  1  1  1 -1]
0.8571428571428571
             precision    recall  f1-score   support

          低       0.67      1.00      0.80         2
          高       1.00      0.80      0.89         5

avg / total       0.90      0.86      0.86         7



In [10]:
####决策树####
from sklearn.tree import DecisionTreeClassifier as DTC
dtc = DTC(criterion='entropy') #建立决策树模型，基于信息熵
dtc.fit(x_train, y_train) #训练模型

DecisionTreeClassifier(class_weight=None, criterion='entropy', max_depth=None,
            max_features=None, max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, presort=False, random_state=None,
            splitter='best')

In [12]:
#导入相关函数，可视化决策树。
#导出的结果是一个dot文件，需要安装Graphviz才能将它转换为pdf或png等格式。
from sklearn.tree import export_graphviz
from sklearn.externals.six import StringIO
with open("tree.dot", 'w') as f:
  f = export_graphviz(dtc, out_file = f)

In [13]:
#测试结果
answer = dtc.predict(x_test)
print(x_test)
print(answer)
print(y_test)
print(np.mean( answer == y_test))
print(classification_report(y_test, answer, target_names = ['低', '高']))

[[ 1  1  1]
 [ 1 -1 -1]
 [ 1  1  1]
 [ 1  1  1]
 [-1  1  1]
 [ 1 -1  1]
 [-1 -1 -1]]
[ 1 -1  1  1  1 -1 -1]
[ 1 -1  1  1  1  1 -1]
0.8571428571428571
             precision    recall  f1-score   support

          低       0.67      1.00      0.80         2
          高       1.00      0.80      0.89         5

avg / total       0.90      0.86      0.86         7

